"""Import the user workbook faithfully. Run with Python + openpyxl; no runtime XLSX dependency."""
from pathlib import Path
import collections
import hashlib
import json
import openpyxl

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'content/es-en/espanol-ingles.xlsx'
book = openpyxl.load_workbook(SOURCE, read_only=True, data_only=True)
units = {}
for row in list(book['Niveles'].values)[1:]:
    if row[0] is None:
        continue
    number = int(row[0])
    if number in units:
        raise ValueError(f'Duplicate level {number}')
    units[number] = {'id': number, 'title': str(row[1]).strip(), 'objective': str(row[2]).strip(), 'wordIds': []}

entries, warnings, duplicates = {}, [], []
for row_number, row in enumerate(list(book['Palabras'].values)[1:], 2):
    if not any(value is not None for value in row):
        continue
    level, _, english, spanish, first, second = row
    if level not in units or any(not isinstance(v, str) or not v.strip() for v in (english, spanish, first, second)):
        raise ValueError(f'Invalid vocabulary at Palabras!{row_number}')
    english, spanish, first, second = (v.strip() for v in (english, spanish, first, second))
    if len({v.casefold() for v in (english, first, second)}) != 3:
        raise ValueError(f'Non-distinct choices at Palabras!{row_number}')
    identity = english.casefold() + '\0' + spanish.casefold()
    word_id = 'es-en-' + hashlib.sha256(identity.encode()).hexdigest()[:20]
    if word_id not in entries:
        entries[word_id] = {'id': word_id, 'spanish': spanish, 'correct': english, 'distractors': [first, second], 'sourceRows': [], 'alternativeDistractors': []}
    else:
        duplicates.append({'row': row_number, 'firstRow': entries[word_id]['sourceRows'][0], 'english': english, 'spanish': spanish})
        entries[word_id]['alternativeDistractors'].append([first, second])
    entries[word_id]['sourceRows'].append(row_number)
    if word_id not in units[level]['wordIds']:
        units[level]['wordIds'].append(word_id)
    if english.casefold() == spanish.casefold():
        warnings.append({'row': row_number, 'english': english, 'spanish': spanish, 'reason': 'Same spelling: may be a valid cognate or a missing translation; requires editorial review.'})

# Keep existing race membership stable when the workbook gains new rows.
manifest_path = SOURCE.parent / 'race-manifest.json'
old = json.loads(manifest_path.read_text(encoding='utf-8')) if manifest_path.exists() else {}
manifest = {}
for number, unit in sorted(units.items()):
    existing = old.get(str(number), [])
    assigned = {word for race in existing for word in race['wordIds']}
    missing = assigned - set(unit['wordIds'])
    if missing:
        raise ValueError(f'Unit {number} removed or changed existing words. Migrate explicitly before importing: {missing}')
    remaining = [word for word in unit['wordIds'] if word not in assigned]
    races = existing.copy()
    for start in range(0, len(remaining), 10):
        races.append({'id': f'es-en-u{number:02d}-r{len(races)+1:03d}', 'wordIds': remaining[start:start+10]})
    unit['races'] = races
    del unit['wordIds']
    manifest[str(number)] = races

data = {'words': list(entries.values()), 'units': list(units.values())}
output = '// Generated by scripts/import-vocabulary.py. Edit the workbook, not this file.\n'
output += 'export const excelCatalog = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n'
(ROOT / 'src/game/data/excelCatalog.ts').write_text(output, encoding='utf-8')
manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
report = {'sourceRows': sum(len(word['sourceRows']) for word in entries.values()), 'uniquePairs': len(entries),
          'units': len(units), 'races': sum(len(unit['races']) for unit in units.values()),
          'duplicates': duplicates, 'translationWarnings': warnings, 'sourceSha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest()}
(SOURCE.parent / 'import-report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(json.dumps({key: value for key, value in report.items() if key not in ('duplicates', 'translationWarnings')}, indent=2))
print(f'{len(duplicates)} duplicate pairs consolidated; {len(warnings)} translations flagged, preserved verbatim.')
